name: 'Test compile for Arduino'
description: 'Compile sketches or Arduino library examples for one board type using arduino-cli and check for errors'
author: 'Armin Joachimsmeyer'
inputs:
  cli-version:
    description: 'Version of arduino-cli to use when builing. Current (3/2020) one is 0.9.0.'
    default: 'latest'
    required: false
    
  sketch-name:
    description: 'Pattern or filename of the sketch(es) to test compile. Useful if the sketch is a *.cpp or *.c file or only one sketch in the repository should be compiled.'
    default: '*.ino'
    required: false
        
  arduino-board-fqbn:
    #In the Arduino IDE, the fqbn is printed in the first line of the verbose output for compilation as parameter -fqbn=... for the "arduino-builder -dump-prefs" command
    description: 'Fully Qualified Board Name of the Arduino board.'
    default: 'arduino:avr:uno'
    required: false
    
  arduino-platform:
    description: 'The platform specifier, if you require a fixed version like arduino:avr@1.8.2 or do not want the specifier derived from the 2 first elements of the arduino-board-fqbn'
    default: ''
    required: false
        
  platform-url:
    description: 'The platform URL for the required board description if arduino-board-fqbn does not start with "arduino:".'
    default: ''
    required: false
    
  required-libraries:
    description: 'Space separated list of arduino library names required for compiling the sketches / examples for this board.'
    default: ''
    required: false

  examples-exclude:
    description: 'List of significant prefixes of all sketches / examples to be excluded in the build for this board.'
    default: ''
    required: false

  examples-build-properties:
    description: |
      Build parameter like `-DDEBUG` for each example in json format
      For example { "WhistleSwitch": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }
    default: ''
    required: false

  debug:
    description: 'If set to "true" she action logs verbose compile output even during successful builds'
    default: ''
    required: false  
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cli-version }}
    - ${{ inputs.sketch-name }}
    - ${{ inputs.arduino-board-fqbn }}
    - ${{ inputs.arduino-platform }}
    - ${{ inputs.platform-url }}
    - ${{ inputs.required-libraries }}
    - ${{ inputs.examples-exclude }}
    - ${{ inputs.examples-build-properties }}
    - ${{ inputs.debug }}
      
branding:
  icon: 'eye'
  color: 'red'